name: bookhouse2
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: any
  cloud_firestore: ^0.12.10+2
  firebase_storage: ^3.0.8
  dio: ^3.0.7
  google_fonts: ^0.1.1
  flutter_swiper : ^1.1.6
  introduction_screen: ^1.0.7
  shared_preferences: ^0.5.6

  cached_network_image: ^2.0.0
  incrementally_loading_listview: ^0.2.0+2
  carousel_slider: ^1.4.1
  pinch_zoom_image: "^0.2.5"







dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
